CREATE RETENTION POLICY "65_days" ON "rpi" DURATION 65d REPLICATION 1 DEFAULT
CREATE RETENTION POLICY "30_days" ON "solaredge" DURATION 65d REPLICATION 1 DEFAULT
CREATE RETENTION POLICY "400_days" ON "solaredge_cloud" DURATION 400d REPLICATION 1 DEFAULT
